dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: segundo-intento-test
  strategy: git
  api_key:
    secure: iWiKP4hIy+qeJ6Eefb3Fvpd3Gq+pABScThyywgrbOowWVIRWgZAy97+tjHeMk789hBtn89fTrNDCOcFD6t2hPNi+8/PD6LNR5CvQGPqEr08QRopiZfEI6IV3IQkwTRauAW/CuFItVst8fG8VopD6kWkJIeif+YIKkBlln4iFC89khix6+ImRPTON31rsZ137pWs9KUdGS5xxvqWVIuTeiTGugvgQtkRwsgNl4o8TVdZrSCs1qvm1mcvQbneX6eYo37W+o2wG30ZbC8wReJEoKG6cMDxrMKI/xpYgQk7ro9MNjBMu/tfNXvNeZFoqMgYWTWgLAJ1MmXQmwemwnVQFa1EieX44WlXT7uVkDsRZojcmeBoE0laj7xPofpPhzffaPpCXOkO+DXbvLcDuBRPajsBEnl25r9NtLT6trYJYa1kFJ9Du4Xj4erepvhuO/RAr6LLWEbJJFNVxnIsSGdtx8ZaHlXWdpqxmJ2xfKcOwdRwUeAbpuptJbKjLKci4Ml9aQ8qypPogMCNqomwKk5OzycLBT/3woOw7LlmdCpZ2wyYnraMtrkiJl1GnXNxdWimWDJWAh+UNQlrMM5dTkOMAPzqobIONvbasg3gBueVjyOR/O/18OPHEYCvtINoFbOFWE4N3QIAtlZo//9kvzfDZ4JX6mpTNdRaNdzfrZE8i3nw=
