dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: segundo-intento-test
  strategy: git
  api_key:
    secure: GTATInVFljrKBrr98aSdSxTeQlLRM8AkhmrQ0g5ATxWc6mSRxszLTc+IbYUb/glGX5Y9TcpubqCnBisN43ggk2WX/jS+et01+DzmJEyw3JijsVK40pNfCswhzOUPJJNb8/zwevRa2xs1jzCw/br9pchQ+SoIERnwu4H/fwqs2uzo/L9xN2/cXCV6eeZrTMf9iIE5aHzTIfQ3ul0XPYKYywmuHit2SPvmTxQ16ILeqHSky4ERqF20pU7/XuLva8Ybftj+i5ioXhrTPv0wCeOR1AZU80oLyWkvbraV7cyi0snhjD7o6eBqERTuLuPQc8cwTpyTGu85V7alIzg4QBZoGeyM7P7eEcEL22YUcOpUK6j8QWerx9GK5/AayoETyJf+owsWrzl2QJNbJqOJL2BOBK9eWf5Rw4tDcFHlMUv7nOjU/jlZQXfRPgWvKSjRKUAbPN9LKsnHnWuhDIFnWtw+ndeR0q2x2TJEhfsBMH9pCauCaWMTpEWc2AwsnNqs7aSDBfXX1Tk2K76Bb1Jxv6khWjEoEH2PUtXrzI4WhmtrUG++ixB/aXmP2yAbKXp2QjGTAzveFiul1Y5RB6SMIQiiFh1SvWwQyy9DUbT149YE/wDV5l8fBQiKwEnND3WF9WPeN8JjKQzvsQMKtZunn/u8h2l3/UrkxXWF5geDwDpFbdg=
